apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo-foo
  labels:
    app: api-demo-foo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-demo-foo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: api-demo-foo
    spec:
      imagePullSecrets:
        - name: myregistrykey 
      containers:
        - name: api-demo-foo
          image: ulisesgascon/simple-api:latest
          ports:
          - containerPort: 3000
          resources:
            requests:
              memory: "100Mi"
              cpu: 100m
            limits:
              cpu: 200m
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /__/health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-foo
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: api-demo-foo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-demo-foo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "api.demo.foo"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: api-demo-foo
            port:
              number: 80